package scs.demos.bigtable.test;


/**
* scs/demos/bigtable/test/Reducer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/bigTable.idl
* Wednesday, December 10, 2008 11:06:00 PM BRST
*/


// nao e pra ser string, string. Isso e so pra testar.
public interface Reducer extends ReducerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reducer
