package scs.demos.philosopher;


/**
* scs/demos/philosopher/ForkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Wednesday, December 10, 2008 9:40:13 AM BRST
*/

public interface ForkOperations 
{
  boolean get ();
  boolean release ();
} // interface ForkOperations
