package scs.demos.philosopher;


/**
* scs/demos/philosopher/ForkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Friday, December 12, 2008 6:43:14 PM BRST
*/

public interface ForkOperations 
{
  boolean get ();
  boolean release ();
} // interface ForkOperations
