package scs.demos.philosopher;


/**
* scs/demos/philosopher/Fork.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Wednesday, December 10, 2008 9:40:13 AM BRST
*/

public interface Fork extends ForkOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Fork
