package scs.demos.philosopher;


/**
* scs/demos/philosopher/ObserverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Wednesday, December 10, 2008 9:40:13 AM BRST
*/

public interface ObserverOperations 
{
  void push (scs.demos.philosopher.StatusInfo info);
} // interface ObserverOperations
