package scs.demos.philosopher;


/**
* scs/demos/philosopher/ObserverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Friday, December 12, 2008 6:43:14 PM BRST
*/

public interface ObserverOperations 
{
  void push (scs.demos.philosopher.StatusInfo info);
} // interface ObserverOperations
