package scs.demos.philosopher;

/**
* scs/demos/philosopher/ObserverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Wednesday, December 10, 2008 9:40:13 AM BRST
*/

public final class ObserverHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.philosopher.Observer value = null;

  public ObserverHolder ()
  {
  }

  public ObserverHolder (scs.demos.philosopher.Observer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.philosopher.ObserverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.philosopher.ObserverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.philosopher.ObserverHelper.type ();
  }

}
