package scs.demos.philosopher;


/**
* scs/demos/philosopher/Philosopher.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Friday, December 12, 2008 6:43:14 PM BRST
*/

public interface Philosopher extends PhilosopherOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Philosopher
