package scs.demos.philosopher;


/**
* scs/demos/philosopher/StatusInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/philosopher.idl
* Wednesday, December 10, 2008 9:40:13 AM BRST
*/

public final class StatusInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public scs.demos.philosopher.PhilosopherState state = null;
  public int ticks_since_last_meal = (int)0;
  public boolean has_left_fork = false;
  public boolean has_right_fork = false;

  public StatusInfo ()
  {
  } // ctor

  public StatusInfo (String _name, scs.demos.philosopher.PhilosopherState _state, int _ticks_since_last_meal, boolean _has_left_fork, boolean _has_right_fork)
  {
    name = _name;
    state = _state;
    ticks_since_last_meal = _ticks_since_last_meal;
    has_left_fork = _has_left_fork;
    has_right_fork = _has_right_fork;
  } // ctor

} // class StatusInfo
