package scs.instrumentation;


/**
* scs/instrumentation/InterfaceStats.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class InterfaceStats implements org.omg.CORBA.portable.IDLEntity
{
  public scs.instrumentation.MethodStats methodStatsCollection[] = null;
  public String interfaceName = null;

  public InterfaceStats ()
  {
  } // ctor

  public InterfaceStats (scs.instrumentation.MethodStats[] _methodStatsCollection, String _interfaceName)
  {
    methodStatsCollection = _methodStatsCollection;
    interfaceName = _interfaceName;
  } // ctor

} // class InterfaceStats
