package scs.instrumentation;


/**
* scs/instrumentation/InterfaceStatsSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class InterfaceStatsSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.instrumentation.InterfaceStats value[] = null;

  public InterfaceStatsSeqHolder ()
  {
  }

  public InterfaceStatsSeqHolder (scs.instrumentation.InterfaceStats[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.instrumentation.InterfaceStatsSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.instrumentation.InterfaceStatsSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.instrumentation.InterfaceStatsSeqHelper.type ();
  }

}
