package scs.instrumentation;


/**
* scs/instrumentation/InterfaceStatsNotAvailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Friday, December 12, 2008 6:43:12 PM BRST
*/

public final class InterfaceStatsNotAvailable extends org.omg.CORBA.UserException
{

  public InterfaceStatsNotAvailable ()
  {
    super(InterfaceStatsNotAvailableHelper.id());
  } // ctor


  public InterfaceStatsNotAvailable (String $reason)
  {
    super(InterfaceStatsNotAvailableHelper.id() + "  " + $reason);
  } // ctor

} // class InterfaceStatsNotAvailable
