package scs.instrumentation;


/**
* scs/instrumentation/InterfaceStatsNotAvailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class InterfaceStatsNotAvailable extends org.omg.CORBA.UserException
{

  public InterfaceStatsNotAvailable ()
  {
    super(InterfaceStatsNotAvailableHelper.id());
  } // ctor


  public InterfaceStatsNotAvailable (String $reason)
  {
    super(InterfaceStatsNotAvailableHelper.id() + "  " + $reason);
  } // ctor

} // class InterfaceStatsNotAvailable
