package scs.instrumentation;

/**
* scs/instrumentation/InterfaceStatsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class InterfaceStatsHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.instrumentation.InterfaceStats value = null;

  public InterfaceStatsHolder ()
  {
  }

  public InterfaceStatsHolder (scs.instrumentation.InterfaceStats initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.instrumentation.InterfaceStatsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.instrumentation.InterfaceStatsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.instrumentation.InterfaceStatsHelper.type ();
  }

}
