package scs.instrumentation;


/**
* scs/instrumentation/IOStatsNotAvailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class IOStatsNotAvailable extends org.omg.CORBA.UserException
{

  public IOStatsNotAvailable ()
  {
    super(IOStatsNotAvailableHelper.id());
  } // ctor


  public IOStatsNotAvailable (String $reason)
  {
    super(IOStatsNotAvailableHelper.id() + "  " + $reason);
  } // ctor

} // class IOStatsNotAvailable
