package scs.instrumentation;


/**
* scs/instrumentation/NetworkStatsNotAvailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class NetworkStatsNotAvailable extends org.omg.CORBA.UserException
{

  public NetworkStatsNotAvailable ()
  {
    super(NetworkStatsNotAvailableHelper.id());
  } // ctor


  public NetworkStatsNotAvailable (String $reason)
  {
    super(NetworkStatsNotAvailableHelper.id() + "  " + $reason);
  } // ctor

} // class NetworkStatsNotAvailable
