package scs.instrumentation;

/**
* scs/instrumentation/StatsCollectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class StatsCollectionHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.instrumentation.StatsCollection value = null;

  public StatsCollectionHolder ()
  {
  }

  public StatsCollectionHolder (scs.instrumentation.StatsCollection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.instrumentation.StatsCollectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.instrumentation.StatsCollectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.instrumentation.StatsCollectionHelper.type ();
  }

}
