package scs.instrumentation;


/**
* scs/instrumentation/StatsCollection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Friday, December 12, 2008 6:43:13 PM BRST
*/

public interface StatsCollection extends StatsCollectionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StatsCollection
