package scs.instrumentation;


/**
* scs/instrumentation/SystemNetworkStats.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class SystemNetworkStats implements org.omg.CORBA.portable.IDLEntity
{
  public long bytesReceived = (long)0;
  public long bytesTransmitted = (long)0;

  public SystemNetworkStats ()
  {
  } // ctor

  public SystemNetworkStats (long _bytesReceived, long _bytesTransmitted)
  {
    bytesReceived = _bytesReceived;
    bytesTransmitted = _bytesTransmitted;
  } // ctor

} // class SystemNetworkStats
