package scs.instrumentation;


/**
* scs/instrumentation/SystemIOStats.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.instrumentation.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class SystemIOStats implements org.omg.CORBA.portable.IDLEntity
{
  public long sectorsRead = (long)0;
  public long timeReading = (long)0;
  public long sectorsWriten = (long)0;
  public long timeWriting = (long)0;
  public long nfsSectorsRead = (long)0;
  public long nfsSectorsWriten = (long)0;

  public SystemIOStats ()
  {
  } // ctor

  public SystemIOStats (long _sectorsRead, long _timeReading, long _sectorsWriten, long _timeWriting, long _nfsSectorsRead, long _nfsSectorsWriten)
  {
    sectorsRead = _sectorsRead;
    timeReading = _timeReading;
    sectorsWriten = _sectorsWriten;
    timeWriting = _timeWriting;
    nfsSectorsRead = _nfsSectorsRead;
    nfsSectorsWriten = _nfsSectorsWriten;
  } // ctor

} // class SystemIOStats
