package scs.event_service;


/**
* scs/event_service/ChannelCollectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Friday, December 12, 2008 6:43:11 PM BRST
*/

public interface ChannelCollectionOperations 
{
  scs.core.IComponent getChannel (String name);
  scs.event_service.ChannelDescr[] getAll ();
} // interface ChannelCollectionOperations
