package scs.event_service;


/**
* scs/event_service/ChannelDescr.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class ChannelDescr implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public scs.core.IComponent channel = null;

  public ChannelDescr ()
  {
  } // ctor

  public ChannelDescr (String _name, scs.core.IComponent _channel)
  {
    name = _name;
    channel = _channel;
  } // ctor

} // class ChannelDescr
