package scs.event_service;


/**
* scs/event_service/ChannelCollectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public interface ChannelCollectionOperations 
{
  scs.core.IComponent getChannel (String name);
  scs.event_service.ChannelDescr[] getAll ();
} // interface ChannelCollectionOperations
