package scs.event_service;

/**
* scs/event_service/ChannelCollectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class ChannelCollectionHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.event_service.ChannelCollection value = null;

  public ChannelCollectionHolder ()
  {
  }

  public ChannelCollectionHolder (scs.event_service.ChannelCollection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.event_service.ChannelCollectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.event_service.ChannelCollectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.event_service.ChannelCollectionHelper.type ();
  }

}
