package scs.event_service;


/**
* scs/event_service/ChannelFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public interface ChannelFactoryOperations 
{
  scs.core.IComponent create (String name) throws scs.event_service.NameAlreadyInUse;
  void destroy (String name) throws scs.event_service.InvalidName;
} // interface ChannelFactoryOperations
