package scs.event_service;


/**
* scs/event_service/ChannelFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Friday, December 12, 2008 6:43:11 PM BRST
*/

public interface ChannelFactoryOperations 
{
  scs.core.IComponent create (String name) throws scs.event_service.NameAlreadyInUse;
  void destroy (String name) throws scs.event_service.InvalidName;
} // interface ChannelFactoryOperations
