package scs.event_service;


/**
* scs/event_service/EventSinkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public interface EventSinkOperations 
{
  void push (org.omg.CORBA.Any ev);
  void disconnect ();
} // interface EventSinkOperations
