package scs.event_service;


/**
* scs/event_service/EventSinkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/events.idl
* Friday, December 12, 2008 6:43:11 PM BRST
*/

public interface EventSinkOperations 
{
  void push (org.omg.CORBA.Any ev);
  void disconnect ();
} // interface EventSinkOperations
