package scs.core;

/**
* scs/core/FacetDescriptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Wednesday, December 10, 2008 9:40:10 AM BRST
*/

public final class FacetDescriptionHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.core.FacetDescription value = null;

  public FacetDescriptionHolder ()
  {
  }

  public FacetDescriptionHolder (scs.core.FacetDescription initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.core.FacetDescriptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.core.FacetDescriptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.core.FacetDescriptionHelper.type ();
  }

}
