package scs.core;


/**
* scs/core/IComponentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Wednesday, December 10, 2008 9:40:10 AM BRST
*/

public interface IComponentOperations 
{
  void startup () throws scs.core.StartupFailed;
  void shutdown () throws scs.core.ShutdownFailed;
  org.omg.CORBA.Object getFacet (String facet_interface);
  org.omg.CORBA.Object getFacetByName (String facet);
  scs.core.ComponentId getComponentId ();
} // interface IComponentOperations
