package scs.core;


/**
* scs/core/IMetaInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Wednesday, December 10, 2008 9:40:10 AM BRST
*/

public interface IMetaInterfaceOperations 
{
  scs.core.FacetDescription[] getFacets ();
  scs.core.FacetDescription[] getFacetsByName (String[] names) throws scs.core.InvalidName;
  scs.core.ReceptacleDescription[] getReceptacles ();
  scs.core.ReceptacleDescription[] getReceptaclesByName (String[] names) throws scs.core.InvalidName;
} // interface IMetaInterfaceOperations
