package scs.core;


/**
* scs/core/InvalidConnection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Friday, December 12, 2008 6:43:10 PM BRST
*/

public final class InvalidConnection extends org.omg.CORBA.UserException
{

  public InvalidConnection ()
  {
    super(InvalidConnectionHelper.id());
  } // ctor


  public InvalidConnection (String $reason)
  {
    super(InvalidConnectionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidConnection
