package scs.core;


/**
* scs/core/InvalidName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Friday, December 12, 2008 6:43:10 PM BRST
*/

public final class InvalidName extends org.omg.CORBA.UserException
{
  public String name = null;

  public InvalidName ()
  {
    super(InvalidNameHelper.id());
  } // ctor

  public InvalidName (String _name)
  {
    super(InvalidNameHelper.id());
    name = _name;
  } // ctor


  public InvalidName (String $reason, String _name)
  {
    super(InvalidNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class InvalidName
