package scs.core;


/**
* scs/core/IReceptaclesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Wednesday, December 10, 2008 9:40:10 AM BRST
*/

public interface IReceptaclesOperations 
{
  int connect (String receptacle, org.omg.CORBA.Object obj) throws scs.core.InvalidName, scs.core.InvalidConnection, scs.core.AlreadyConnected, scs.core.ExceededConnectionLimit;
  void disconnect (int id) throws scs.core.InvalidConnection, scs.core.NoConnection;
  scs.core.ConnectionDescription[] getConnections (String receptacle) throws scs.core.InvalidName;
} // interface IReceptaclesOperations
