package scs.core;


/**
* scs/core/NoConnection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Friday, December 12, 2008 6:43:10 PM BRST
*/

public final class NoConnection extends org.omg.CORBA.UserException
{

  public NoConnection ()
  {
    super(NoConnectionHelper.id());
  } // ctor


  public NoConnection (String $reason)
  {
    super(NoConnectionHelper.id() + "  " + $reason);
  } // ctor

} // class NoConnection
