package scs.core;


/**
* scs/core/ReceptacleDescription.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Friday, December 12, 2008 6:43:10 PM BRST
*/

public final class ReceptacleDescription implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String interface_name = null;
  public boolean is_multiplex = false;
  public scs.core.ConnectionDescription connections[] = null;

  public ReceptacleDescription ()
  {
  } // ctor

  public ReceptacleDescription (String _name, String _interface_name, boolean _is_multiplex, scs.core.ConnectionDescription[] _connections)
  {
    name = _name;
    interface_name = _interface_name;
    is_multiplex = _is_multiplex;
    connections = _connections;
  } // ctor

} // class ReceptacleDescription
