package scs.core;


/**
* scs/core/ShutdownFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Friday, December 12, 2008 6:43:10 PM BRST
*/

public final class ShutdownFailed extends org.omg.CORBA.UserException
{

  public ShutdownFailed ()
  {
    super(ShutdownFailedHelper.id());
  } // ctor


  public ShutdownFailed (String $reason)
  {
    super(ShutdownFailedHelper.id() + "  " + $reason);
  } // ctor

} // class ShutdownFailed
