package scs.core;


/**
* scs/core/StartupFailed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/scs.idl
* Wednesday, December 10, 2008 9:40:10 AM BRST
*/

public final class StartupFailed extends org.omg.CORBA.UserException
{

  public StartupFailed ()
  {
    super(StartupFailedHelper.id());
  } // ctor


  public StartupFailed (String $reason)
  {
    super(StartupFailedHelper.id() + "  " + $reason);
  } // ctor

} // class StartupFailed
