package scs.reasoning;


/**
* scs/reasoning/DataCollectionFailure.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class DataCollectionFailure extends org.omg.CORBA.UserException
{

  public DataCollectionFailure ()
  {
    super(DataCollectionFailureHelper.id());
  } // ctor


  public DataCollectionFailure (String $reason)
  {
    super(DataCollectionFailureHelper.id() + "  " + $reason);
  } // ctor

} // class DataCollectionFailure
