package scs.reasoning;


/**
* scs/reasoning/MetricDescription.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Friday, December 12, 2008 6:43:13 PM BRST
*/

public final class MetricDescription implements org.omg.CORBA.portable.IDLEntity
{
  public String metricName = null;
  public double metricValue = (double)0;

  public MetricDescription ()
  {
  } // ctor

  public MetricDescription (String _metricName, double _metricValue)
  {
    metricName = _metricName;
    metricValue = _metricValue;
  } // ctor

} // class MetricDescription
