package scs.reasoning;


/**
* scs/reasoning/MonitorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Friday, December 12, 2008 6:43:13 PM BRST
*/

public interface MonitorOperations 
{
  boolean prepareToDataCollection (scs.reasoning.DataCollectionProperty props);
  void startDataCollection ();
  void finishDataCollection ();
  String getSystemState ();
  boolean ping ();
  String getNode ();
  void setNode (String name);
} // interface MonitorOperations
