package scs.reasoning;

/**
* scs/reasoning/ReasoningHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Friday, December 12, 2008 6:43:13 PM BRST
*/

public final class ReasoningHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.reasoning.Reasoning value = null;

  public ReasoningHolder ()
  {
  }

  public ReasoningHolder (scs.reasoning.Reasoning initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.reasoning.ReasoningHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.reasoning.ReasoningHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.reasoning.ReasoningHelper.type ();
  }

}
