package scs.reasoning;

/**
* scs/reasoning/SystemStateValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Wednesday, December 10, 2008 9:40:12 AM BRST
*/

public final class SystemStateValueHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.reasoning.SystemStateValue value = null;

  public SystemStateValueHolder ()
  {
  }

  public SystemStateValueHolder (scs.reasoning.SystemStateValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.reasoning.SystemStateValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.reasoning.SystemStateValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.reasoning.SystemStateValueHelper.type ();
  }

}
