package scs.reasoning;


/**
* scs/reasoning/UnlabeledHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/reasoning.idl
* Friday, December 12, 2008 6:43:13 PM BRST
*/

public final class UnlabeledHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public UnlabeledHolder ()
  {
  }

  public UnlabeledHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.reasoning.UnlabeledHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.reasoning.UnlabeledHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.reasoning.UnlabeledHelper.type ();
  }

}
