package scs.demos.bigtable;


/**
* scs/demos/bigtable/Config.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/bigTable.idl
* Friday, December 12, 2008 6:43:15 PM BRST
*/

public interface Config extends ConfigOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Config
