package scs.demos.bigtable;


/**
* scs/demos/bigtable/ConfigOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/bigTable.idl
* Saturday, December 13, 2008 1:04:31 PM BRST
*/

public interface ConfigOperations 
{
  void setName (String name);
  void addReducer (org.omg.CORBA.Any reducer);
} // interface ConfigOperations
