package scs.demos.bigtable;


/**
* scs/demos/bigtable/SorterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/bigTable.idl
* Saturday, December 13, 2008 1:04:31 PM BRST
*/

public interface SorterOperations 
{
  void put (org.omg.CORBA.Any key, org.omg.CORBA.Any value);
  void get (org.omg.CORBA.Any key, scs.demos.bigtable.IteratorHolder values);

  //void getKeysOnRange(in long reducerId, out Keys keys);
  void getEntriesOnRange (scs.demos.bigtable.AllEntriesHolder allEntries);
  void setNumberOfReducers (int numReducers);
} // interface SorterOperations
