package scs.demos.bigtable;


/**
* scs/demos/bigtable/SorterPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/bigTable.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/

public class SorterPOATie extends SorterPOA
{

  // Constructors

  public SorterPOATie ( scs.demos.bigtable.SorterOperations delegate ) {
      this._impl = delegate;
  }
  public SorterPOATie ( scs.demos.bigtable.SorterOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.demos.bigtable.SorterOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.demos.bigtable.SorterOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }

  // nao e pra ser string, string. Isso e so pra testar.
  public void sort (String key, String values)
  {
    _impl.sort(key, values);
  } // sort

  public void start ()
  {
    _impl.start();
  } // start

  private scs.demos.bigtable.SorterOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class SorterPOATie
