package scs.demos.bigtable;


/**
* scs/demos/bigtable/Sorter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/bigTable.idl
* Friday, December 12, 2008 4:48:32 PM BRST
*/

public interface Sorter extends SorterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sorter
