package scs.demos.bigtable;


/**
* scs/demos/bigtable/SorterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/bigTable.idl
* Saturday, December 6, 2008 8:01:09 PM BRST
*/

public interface SorterOperations 
{

  // nao e pra ser string, string. Isso e so pra testar.
  void sort (String key, String values);
  void start ();
} // interface SorterOperations
