package scs.demos.bigtable;


/**
* scs/demos/bigtable/Sorter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/bigTable.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/

public interface Sorter extends SorterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sorter
