package scs.container;


/**
* scs/container/ComponentAlreadyLoaded.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Friday, December 12, 2008 6:43:12 PM BRST
*/

public final class ComponentAlreadyLoaded extends org.omg.CORBA.UserException
{

  public ComponentAlreadyLoaded ()
  {
    super(ComponentAlreadyLoadedHelper.id());
  } // ctor


  public ComponentAlreadyLoaded (String $reason)
  {
    super(ComponentAlreadyLoadedHelper.id() + "  " + $reason);
  } // ctor

} // class ComponentAlreadyLoaded
