package scs.container;


/**
* scs/container/ComponentSuspension.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Friday, December 12, 2008 6:43:12 PM BRST
*/

public interface ComponentSuspension extends ComponentSuspensionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ComponentSuspension
