package scs.container;


/**
* scs/container/ComponentSuspensionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public interface ComponentSuspensionOperations 
{

  // a negative number means a suspension (yields coroutines)
  void suspend ();
  void halt ();
  void resume ();
  int getStatus ();
} // interface ComponentSuspensionOperations
