package scs.container;


/**
* scs/container/ComponentCollectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public interface ComponentCollectionOperations 
{
  scs.container.ComponentHandle[] getComponent (scs.core.ComponentId id);
  scs.container.ComponentHandle[] getComponents ();
} // interface ComponentCollectionOperations
