package scs.container;


/**
* scs/container/ComponentCollectionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Friday, December 12, 2008 6:43:12 PM BRST
*/

public interface ComponentCollectionOperations 
{
  scs.container.ComponentHandle[] getComponent (scs.core.ComponentId id);
  scs.container.ComponentHandle[] getComponents ();
} // interface ComponentCollectionOperations
