package scs.container;

/**
* scs/container/InterceptorNotInstalledHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class InterceptorNotInstalledHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.container.InterceptorNotInstalled value = null;

  public InterceptorNotInstalledHolder ()
  {
  }

  public InterceptorNotInstalledHolder (scs.container.InterceptorNotInstalled initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.container.InterceptorNotInstalledHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.container.InterceptorNotInstalledHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.container.InterceptorNotInstalledHelper.type ();
  }

}
