package scs.container;


/**
* scs/container/InterceptorIdsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class InterceptorIdsHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public InterceptorIdsHolder ()
  {
  }

  public InterceptorIdsHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.container.InterceptorIdsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.container.InterceptorIdsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.container.InterceptorIdsHelper.type ();
  }

}
