package scs.container;


/**
* scs/container/ListLockFail.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class ListLockFail extends org.omg.CORBA.UserException
{

  public ListLockFail ()
  {
    super(ListLockFailHelper.id());
  } // ctor


  public ListLockFail (String $reason)
  {
    super(ListLockFailHelper.id() + "  " + $reason);
  } // ctor

} // class ListLockFail
