package scs.container;


/**
* scs/container/LoadFailure.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class LoadFailure extends org.omg.CORBA.UserException
{

  public LoadFailure ()
  {
    super(LoadFailureHelper.id());
  } // ctor


  public LoadFailure (String $reason)
  {
    super(LoadFailureHelper.id() + "  " + $reason);
  } // ctor

} // class LoadFailure
