package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/ConectionToExecNodesException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/

public final class ConectionToExecNodesException extends org.omg.CORBA.UserException
{

  public ConectionToExecNodesException ()
  {
    super(ConectionToExecNodesExceptionHelper.id());
  } // ctor


  public ConectionToExecNodesException (String $reason)
  {
    super(ConectionToExecNodesExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class ConectionToExecNodesException
