package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/FileSplit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/


// Representa uma particao do arquivo de entrada
public interface FileSplit extends FileSplitOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSplit
