package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/FileSplitOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/


// Representa uma particao do arquivo de entrada
public interface FileSplitOperations 
{
  String getPath ();
  long getLength ();
} // interface FileSplitOperations
