package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/IOFormatException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/

public final class IOFormatException extends org.omg.CORBA.UserException
{

  public IOFormatException ()
  {
    super(IOFormatExceptionHelper.id());
  } // ctor


  public IOFormatException (String $reason)
  {
    super(IOFormatExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class IOFormatException
