package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/IOFormatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/


//Descreve a entrada-saida do processo mapreduce
public interface IOFormatOperations 
{
  scs.demos.mapreduce.RecordReader getRecordReader (scs.demos.mapreduce.TaskStatus status) throws scs.demos.mapreduce.IOFormatException;
  scs.demos.mapreduce.RecordWriter getRecordWriter (scs.demos.mapreduce.TaskStatus status) throws scs.demos.mapreduce.IOFormatException;
  scs.demos.mapreduce.FileSplit[] getSplits (String confFileName, scs.demos.mapreduce.Reporter reporter) throws scs.demos.mapreduce.SplitException;
} // interface IOFormatOperations
