package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/Partitioner.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/


//Define a operacao para distribuir chaves para os reducers
public interface Partitioner extends PartitionerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Partitioner
