package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/RecordWriter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/


//Define operacoes para escrever pares <key, value>
public interface RecordWriter extends RecordWriterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RecordWriter
