package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/RecordReaderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/


//Define operacoes para ler pares <key, value>
public interface RecordReaderOperations 
{
  void open (String confFileName, scs.demos.mapreduce.FileSplit fileSplit, scs.demos.mapreduce.Reporter reporter) throws scs.demos.mapreduce.IOMapReduceException;
  boolean next (org.omg.CORBA.AnyHolder key, org.omg.CORBA.AnyHolder value) throws scs.demos.mapreduce.IOMapReduceException;
  void close () throws scs.demos.mapreduce.IOMapReduceException;
  scs.demos.mapreduce.FileSplit getFileSplit ();
} // interface RecordReaderOperations
