package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/ReducerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/


// Define a operacao reduce
public class ReducerPOATie extends ReducerPOA
{

  // Constructors

  public ReducerPOATie ( scs.demos.mapreduce.ReducerOperations delegate ) {
      this._impl = delegate;
  }
  public ReducerPOATie ( scs.demos.mapreduce.ReducerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.demos.mapreduce.ReducerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.demos.mapreduce.ReducerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void reduce (scs.demos.mapreduce.OutputCollector collector, scs.demos.mapreduce.Reporter reporter, scs.demos.bigtable.Sorter sorter) throws scs.demos.mapreduce.IOMapReduceException
  {
    _impl.reduce(collector, reporter, sorter);
  } // reduce

  private scs.demos.mapreduce.ReducerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ReducerPOATie
