package scs.demos.mapreduce;

/**
* scs/demos/mapreduce/ReducerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/


// Define a operacao reduce
public final class ReducerHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.mapreduce.Reducer value = null;

  public ReducerHolder ()
  {
  }

  public ReducerHolder (scs.demos.mapreduce.Reducer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.mapreduce.ReducerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.mapreduce.ReducerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.mapreduce.ReducerHelper.type ();
  }

}
