package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/ReducerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/


// Define a operacao reduce
public interface ReducerOperations 
{
  void reduce (scs.demos.mapreduce.OutputCollector collector, scs.demos.mapreduce.Reporter reporter, scs.demos.bigtable.Sorter sorter) throws scs.demos.mapreduce.IOMapReduceException;
} // interface ReducerOperations
