package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/ReducerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/


// Define a operacao reduce
public interface ReducerOperations 
{
  void reduce (org.omg.CORBA.Any key, org.omg.CORBA.Any[] values, scs.demos.mapreduce.OutputCollector collector, scs.demos.mapreduce.Reporter reporter) throws scs.demos.mapreduce.IOMapReduceException;
} // interface ReducerOperations
