package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/Reporter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/


//Reporta log de mensagens de operacoes
public interface Reporter extends ReporterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reporter
