package scs.demos.mapreduce;

/**
* scs/demos/mapreduce/StartFailureExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/

public final class StartFailureExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.mapreduce.StartFailureException value = null;

  public StartFailureExceptionHolder ()
  {
  }

  public StartFailureExceptionHolder (scs.demos.mapreduce.StartFailureException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.mapreduce.StartFailureExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.mapreduce.StartFailureExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.mapreduce.StartFailureExceptionHelper.type ();
  }

}
