package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/TaskInstantiationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/

public final class TaskInstantiationException extends org.omg.CORBA.UserException
{

  public TaskInstantiationException ()
  {
    super(TaskInstantiationExceptionHelper.id());
  } // ctor


  public TaskInstantiationException (String $reason)
  {
    super(TaskInstantiationExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class TaskInstantiationException
