package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/TaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/

public interface TaskOperations 
{
  int getId ();
  void setStatus (scs.demos.mapreduce.TaskStatus status);
  void setOutput (scs.demos.mapreduce.FileSplit[] output);
  scs.demos.mapreduce.TaskStatus getStatus ();
  scs.demos.mapreduce.FileSplit[] getInput ();
  scs.demos.mapreduce.FileSplit[] getOutput ();
  int getReduceIndex ();
} // interface TaskOperations
