package scs.demos.mapreduce;

/**
* scs/demos/mapreduce/TaskInstantiationExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/

public final class TaskInstantiationExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.demos.mapreduce.TaskInstantiationException value = null;

  public TaskInstantiationExceptionHolder ()
  {
  }

  public TaskInstantiationExceptionHolder (scs.demos.mapreduce.TaskInstantiationException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.demos.mapreduce.TaskInstantiationExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.demos.mapreduce.TaskInstantiationExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.demos.mapreduce.TaskInstantiationExceptionHelper.type ();
  }

}
