package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/WorkerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/

public interface WorkerOperations 
{
  boolean start (String configFileName, String nodeName, scs.core.IComponent channel, scs.demos.mapreduce.Reporter reporter, scs.core.IComponent workerComponent);
  void execute (scs.demos.mapreduce.Task task);
  String getNode ();
  boolean ping ();
} // interface WorkerOperations
