package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/WorkerInstantiationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/

public final class WorkerInstantiationException extends org.omg.CORBA.UserException
{

  public WorkerInstantiationException ()
  {
    super(WorkerInstantiationExceptionHelper.id());
  } // ctor


  public WorkerInstantiationException (String $reason)
  {
    super(WorkerInstantiationExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class WorkerInstantiationException
