package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/WorkerPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Friday, December 12, 2008 6:43:16 PM BRST
*/

public class WorkerPOATie extends WorkerPOA
{

  // Constructors

  public WorkerPOATie ( scs.demos.mapreduce.WorkerOperations delegate ) {
      this._impl = delegate;
  }
  public WorkerPOATie ( scs.demos.mapreduce.WorkerOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public scs.demos.mapreduce.WorkerOperations _delegate() {
      return this._impl;
  }
  public void _delegate (scs.demos.mapreduce.WorkerOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean start (String configFileName, String nodeName, scs.core.IComponent channel, scs.demos.mapreduce.Reporter reporter, scs.core.IComponent workerComponent)
  {
    return _impl.start(configFileName, nodeName, channel, reporter, workerComponent);
  } // start

  public void execute (scs.demos.mapreduce.Task task)
  {
    _impl.execute(task);
  } // execute

  public String getNode ()
  {
    return _impl.getNode();
  } // getNode

  public boolean ping ()
  {
    return _impl.ping();
  } // ping

  private scs.demos.mapreduce.WorkerOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class WorkerPOATie
