package scs.demos.mapreduce;


/**
* scs/demos/mapreduce/WorkerInstantiationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/mapReduce.idl
* Wednesday, December 10, 2008 9:40:14 AM BRST
*/

public final class WorkerInstantiationException extends org.omg.CORBA.UserException
{

  public WorkerInstantiationException ()
  {
    super(WorkerInstantiationExceptionHelper.id());
  } // ctor


  public WorkerInstantiationException (String $reason)
  {
    super(WorkerInstantiationExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class WorkerInstantiationException
