module scs {
	module demos {
		module bigtable {
			typedef sequence<any> Iterator;
			typedef sequence<string> Keys;
			struct Entries { 
			    any key; 
			    sequence<any> values;
			};
			typedef sequence<Entries> AllEntries;

			interface Sorter {
				void put(in any key, in any value);
				void get(in any key, out Iterator values);
				//void getKeysOnRange(in long reducerId, out Keys keys);
				void getEntriesOnRange(out AllEntries allEntries);
				void setNumberOfReducers(in long numReducers);
				//void start();
			};

			interface Config {
				void setName(in string name);
				void addReducer(in any reducer);
			};

			module test {
				typedef sequence<any> Iterator;

				// Simula a conexao a um reducer
				// Alteracoes na interface em relacao ao mapreduce sao de fato necessarias?
				// nao e pra ser string, string. Isso e so pra testar.
				interface Reducer {
				    	void reduce (in string key, in string values);
				};
			};
		};
	};
};

