package scs.auxiliar;


/**
* scs/auxiliar/ComponentProperties.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public interface ComponentProperties extends ComponentPropertiesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ComponentProperties
