package scs.auxiliar;


/**
* scs/auxiliar/ComponentHelpOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public interface ComponentHelpOperations 
{
  String getHelpInfo (scs.core.ComponentId id) throws scs.container.ComponentNotFound, scs.auxiliar.HelpInfoNotAvailable;
} // interface ComponentHelpOperations
