package scs.auxiliar;

/**
* scs/auxiliar/HelpInfoNotAvailableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class HelpInfoNotAvailableHolder implements org.omg.CORBA.portable.Streamable
{
  public scs.auxiliar.HelpInfoNotAvailable value = null;

  public HelpInfoNotAvailableHolder ()
  {
  }

  public HelpInfoNotAvailableHolder (scs.auxiliar.HelpInfoNotAvailable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = scs.auxiliar.HelpInfoNotAvailableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    scs.auxiliar.HelpInfoNotAvailableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return scs.auxiliar.HelpInfoNotAvailableHelper.type ();
  }

}
