package scs.auxiliar;


/**
* scs/auxiliar/HelpInfoNotAvailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class HelpInfoNotAvailable extends org.omg.CORBA.UserException
{

  public HelpInfoNotAvailable ()
  {
    super(HelpInfoNotAvailableHelper.id());
  } // ctor


  public HelpInfoNotAvailable (String $reason)
  {
    super(HelpInfoNotAvailableHelper.id() + "  " + $reason);
  } // ctor

} // class HelpInfoNotAvailable
