package scs.auxiliar;


/**
* scs/auxiliar/ReadOnlyProperty.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class ReadOnlyProperty extends org.omg.CORBA.UserException
{

  public ReadOnlyProperty ()
  {
    super(ReadOnlyPropertyHelper.id());
  } // ctor


  public ReadOnlyProperty (String $reason)
  {
    super(ReadOnlyPropertyHelper.id() + "  " + $reason);
  } // ctor

} // class ReadOnlyProperty
