package scs.auxiliar;


/**
* scs/auxiliar/UndefinedProperty.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Friday, December 12, 2008 6:43:12 PM BRST
*/

public final class UndefinedProperty extends org.omg.CORBA.UserException
{

  public UndefinedProperty ()
  {
    super(UndefinedPropertyHelper.id());
  } // ctor


  public UndefinedProperty (String $reason)
  {
    super(UndefinedPropertyHelper.id() + "  " + $reason);
  } // ctor

} // class UndefinedProperty
