package scs.execution_node;


/**
* scs/execution_node/ExecutionNode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Friday, December 12, 2008 6:43:12 PM BRST
*/

public interface ExecutionNode extends ExecutionNodeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ExecutionNode
