package scs.execution_node;


/**
* scs/execution_node/InvalidProperty.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class InvalidProperty extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InvalidProperty ()
  {
    super(InvalidPropertyHelper.id());
  } // ctor

  public InvalidProperty (String _reason)
  {
    super(InvalidPropertyHelper.id());
    reason = _reason;
  } // ctor


  public InvalidProperty (String $reason, String _reason)
  {
    super(InvalidPropertyHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InvalidProperty
