package scs.execution_node;


/**
* scs/execution_node/RequirementNotMet.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../idl/deployment.idl
* Wednesday, December 10, 2008 9:40:11 AM BRST
*/

public final class RequirementNotMet extends org.omg.CORBA.UserException
{
  public String reason = null;

  public RequirementNotMet ()
  {
    super(RequirementNotMetHelper.id());
  } // ctor

  public RequirementNotMet (String _reason)
  {
    super(RequirementNotMetHelper.id());
    reason = _reason;
  } // ctor


  public RequirementNotMet (String $reason, String _reason)
  {
    super(RequirementNotMetHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class RequirementNotMet
